const AVAILABLE_BALANCE_PREFERENCE = 2;
const BOOKED_BALANCE_PREFERENCE = 1;
const UNKNOWN_BALANCE_PREFERENCE = 0;

const BALANCE_PREFERENCES: Readonly<Record<string, number>> = {
	AVAILABLE: AVAILABLE_BALANCE_PREFERENCE,
	AVAILABLEBALANCE: AVAILABLE_BALANCE_PREFERENCE,
	CLAV: AVAILABLE_BALANCE_PREFERENCE,
	CLOSINGAVAILABLE: AVAILABLE_BALANCE_PREFERENCE,
	FORWARDAVAILABLE: AVAILABLE_BALANCE_PREFERENCE,
	FWAV: AVAILABLE_BALANCE_PREFERENCE,
	INTERIMAVAILABLE: AVAILABLE_BALANCE_PREFERENCE,
	ITAV: AVAILABLE_BALANCE_PREFERENCE,
	OPAV: AVAILABLE_BALANCE_PREFERENCE,
	OPENINGAVAILABLE: AVAILABLE_BALANCE_PREFERENCE,
	BOOKED: BOOKED_BALANCE_PREFERENCE,
	BOOKEDBALANCE: BOOKED_BALANCE_PREFERENCE,
	CLBD: BOOKED_BALANCE_PREFERENCE,
	CLOSINGBOOKED: BOOKED_BALANCE_PREFERENCE,
	INTERIMBOOKED: BOOKED_BALANCE_PREFERENCE,
	ITBD: BOOKED_BALANCE_PREFERENCE,
	OPBD: BOOKED_BALANCE_PREFERENCE,
	OPENINGBOOKED: BOOKED_BALANCE_PREFERENCE,
	PRCD: BOOKED_BALANCE_PREFERENCE,
	INFO: UNKNOWN_BALANCE_PREFERENCE,
	OTHR: UNKNOWN_BALANCE_PREFERENCE,
	XPCD: UNKNOWN_BALANCE_PREFERENCE,
};

export function getBalancePreference(balanceType: string): number {
	const normalizedType = balanceType
		.trim()
		.toUpperCase()
		.replace(/[\s_-]+/g, '');
	const preference = BALANCE_PREFERENCES[normalizedType];
	return typeof preference === 'number' ? preference : UNKNOWN_BALANCE_PREFERENCE;
}

export function truncate(value: string | null | undefined, length: number): string | null {
	return value ? value.slice(0, length) : null;
}
